package org.ual.hmis.Group_19_KacperDawid;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModifyTaskTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    System.setProperty("webdriver.gecko.driver", "drivers/geckodriver-v0.33.0-win-aarch64/geckodriver.exe");
    System.setProperty("webdriver.chrome.driver", "drivers/chromedriver_win32/chromedriver.exe");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modifyTask() {
    // Test name: modifyTask
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/#/Home | 
    driver.get("http://localhost:8080/#/Home");
    // 2 | setWindowSize | 1064x808 | 
    driver.manage().window().setSize(new Dimension(1064, 808));
    // 3 | click | css=li:nth-child(2) > .nav-link | 
    driver.findElement(By.cssSelector("li:nth-child(2) > .nav-link")).click();
    // 4 | click | css=.list-group-item:nth-child(1) .btn-success | 
    driver.findElement(By.cssSelector(".list-group-item:nth-child(1) .btn-success")).click();
    // 5 | click | xpath=//body | 
    driver.findElement(By.xpath("//body")).click();
    // 6 | type | css=.ng-dirty | 12311
    driver.findElement(By.cssSelector(".ng-dirty")).sendKeys("12311");
    // 7 | click | css=.list-group-item:nth-child(1) .btn-primary | 
    driver.findElement(By.cssSelector(".list-group-item:nth-child(1) .btn-primary")).click();
  }
}
